spring.application.name=SecurityApp

spring.datasource.url=jdbc:mysql://localhost:3306/springsecurity?useSSL=false
spring.datasource.username=root
spring.datasource.password=Nitu@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8083

#//security config

spring.security.user.name=Nitu
spring.security.user.password=

#//google oauth config

#JWT Token
jwt.secretKey=mySecretKeyForJwtAuthenticationMustBeAtLeast32CharactersLong
deploy.env=development